#!/usr/bin/env bash
# Configure domain zones
subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"
digCommand() {
 dig "$domain.$sub" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$domain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}
if [ $# -eq 1 ]; then
	for subs in "${subdomains[@]}"; do
		dig_cmd "$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	dig_cmd "$domain" "$sub"
fi
