#!/usr/bin/env bash
# This script shows "Best School" 10 times 
#but for the 9th iteration display Best School and "Hi" on a new line
i=0
while ((i < 10))
do
	if [[ $i -eq 9 ]]
	then 
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
