#!/usr/bin/env bash
# This script loops from 1 to 10 and for the 4th iteration display 'bad luck' 
# and 'good luck' for 8th iteration. 'Best school' for the other iterations
i=0
while ((i < 10))
do
	if [[ $i -eq 3 ]]
	then 
		echo "bad luck"
	elif [[ $i -eq 7 ]]
	then 
	        echo "good luck" 
	else
		echo "Best School"
	fi
	((i++))
done
