#!/usr/bin/env bash
# This script loops from 1 to 20 and display some text on some iterations
i=1
while ((i <= 20))
do
        echo $i
	case $i in 
	     "4")
	          echo "bad luck from China";;
	     "9")
	          echo "good luck from Japan";;
              "17")
	         echo "bad luck from Italy";;
	esac
	((i++))
done
